.TH COPY 1 "05 January 21"
.SH NAME
sb \- configure vi automatically
.SH SYNOPSIS
\fBsb\fP [\fIOPTION\fP] [\fIFILE\fP] ...
.SH DESCRIPTION
A shell script used to generate vi's configuratin.
.TP
\fB\-e\fP translate m4 macros to ex language 
.TP
\fB\-m\fP translate sb-style configuration to m4 macros
.TP
\fB\-t\fP used for testing, output vi's configuration instead of entering vi
.SH AUTHOR
Writen by Maeda Chu
.SH "SEE ALSO"
vi(1), ex(1), m4(1), sed(1)

